version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=user
     - MYSQL_PASSWORD=pass
     - MYSQL_DATABASE=testdb
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=pass
     - RABBITMQ_DEFAULT_VHOST=testvhost
  config:
    image: benwilcock/config-service
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production