server:
  port: 9001

message: Greetings from the PRODUCT-COMMAND-SIDE microservice [using the LOCAL FILE config].

spring:
    application:
        exchange: product.events.fanout.exchange
        queue: product.default.queue

logging:
  level:
    org:
      springframework:
        web: INFO
    io:
      benwilcock: INFO